from __future__ import annotations
import json, os, shutil, subprocess, sys, time
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'output'
KDIR=ROOT/'.kaggle_worker'
DDIR=ROOT/'.kaggle_dataset'
INPUT_DATASET='bhajanaabha/hindibhajans-echomimic-inputs'
KERNEL_PREFIX='bhajanaabha/hindibhajans-musetalk'

def run(cmd,env):
    print('RUN:',*cmd,flush=True)
    p=subprocess.run(cmd,cwd=ROOT,env=env,text=True,capture_output=True)
    if p.stdout:
        print(p.stdout,end='',flush=True)
    if p.stderr:
        print(p.stderr,end='',flush=True)
    return p

def wait_dataset(env,timeout=900):
    deadline=time.time()+timeout
    while time.time()<deadline:
        p=subprocess.run(['kaggle','datasets','status',INPUT_DATASET,'--format','json'],cwd=ROOT,env=env,capture_output=True,text=True)
        s=(p.stdout+p.stderr).strip(); print('DATASET_STATUS',s,flush=True)
        if p.returncode==0:
            low=s.lower()
            if any(x in low for x in ('complete','ready','success')): return
            if any(x in low for x in ('error','failed','cancelled','canceled')): raise RuntimeError('KAGGLE_DATASET_FAILED '+s)
        time.sleep(15)
    raise TimeoutError('KAGGLE_DATASET_TIMEOUT')

def publish_inputs(env,image,audio,seconds):
    shutil.rmtree(DDIR,ignore_errors=True); DDIR.mkdir(parents=True)
    shutil.copy2(image,DDIR/'singer.png'); shutil.copy2(audio,DDIR/'bhajan.mp3'); (DDIR/'duration.txt').write_text(str(seconds))
    (DDIR/'dataset-metadata.json').write_text(json.dumps({
        'title':'HindiBHajans EchoMimic Runtime Inputs','id':INPUT_DATASET,
        'subtitle':'Private per-run inputs shared with the video worker',
        'description':'Private runtime input package generated by GitHub Actions.',
        'licenses':[{'name':'other'}]},indent=2))
    st=subprocess.run(['kaggle','datasets','status',INPUT_DATASET,'--format','json'],cwd=ROOT,env=env,capture_output=True,text=True)
    if st.returncode==0:
        run(['kaggle','datasets','version','-p',str(DDIR),'-m',f'MuseTalk runtime inputs {seconds}s','-d'],env)
    else:
        run(['kaggle','datasets','create','-p',str(DDIR)],env)
    wait_dataset(env)

def wait_kernel(env,kernel):
    deadline=time.time()+12*60*60
    while time.time()<deadline:
        p=subprocess.run(['kaggle','kernels','status',kernel],cwd=ROOT,env=env,capture_output=True,text=True)
        status=(p.stdout+p.stderr).strip(); print(status,flush=True); low=status.lower()
        if 'complete' in low and not any(x in low for x in ('incomplete','not complete')): return True,status
        if any(x in low for x in ('error','failed','cancelled','canceled','cancel_acknowledged','cancel acknowledged')):
            log=subprocess.run(['kaggle','kernels','logs',kernel],cwd=ROOT,env=env,capture_output=True,text=True)
            return False,f'KAGGLE_KERNEL_TERMINAL_FAILURE status={status}\n{log.stdout or log.stderr}'
        time.sleep(30)
    return False,'KAGGLE_KERNEL_TIMEOUT'

def run_kernel(env,kernel):
    shutil.rmtree(KDIR,ignore_errors=True); KDIR.mkdir(parents=True)
    shutil.copy2(ROOT/'app'/'kaggle_echomimic_worker.py',KDIR/'worker.py')
    meta={'id':kernel,'title':kernel.rsplit('/',1)[-1],'code_file':'worker.py','language':'python','kernel_type':'script',
          'is_private':True,'enable_gpu':True,'enable_internet':True,'machine_shape':'NvidiaTeslaT4',
          'dataset_sources':[INPUT_DATASET],'competition_sources':[],'kernel_sources':[],'model_sources':[]}
    (KDIR/'kernel-metadata.json').write_text(json.dumps(meta,indent=2))
    run([sys.executable,'-m','py_compile',str(KDIR/'worker.py')],env)
    push=run(['kaggle','kernels','push','-p',str(KDIR),'--timeout',str(12*60*60)],env)
    push_text=(push.stdout or '')+'\n'+(push.stderr or '')
    low=push_text.lower()
    if 'maximum weekly gpu quota' in low or ('gpu quota' in low and 'reached' in low):
        raise RuntimeError('KAGGLE_GPU_QUOTA_EXHAUSTED: Kaggle refused GPU allocation before the MuseTalk kernel was created. Do not retry; wait for quota reset.')
    if push.returncode != 0:
        raise RuntimeError(f'KAGGLE_KERNEL_PUSH_FAILED: {push_text.strip()}')
    return wait_kernel(env,kernel)

def main(seconds):
    token=os.getenv('KAGGLE_API_TOKEN') or os.getenv('KAGGLE_API_TOKEN3')
    if not token: raise RuntimeError('KAGGLE_API_TOKEN missing')
    image=ROOT/'assets'/'singer_image.png'; audio=OUT/'bhajan_source.mp3'
    if not image.exists() or not audio.exists(): raise RuntimeError('canonical inputs missing')
    if not 180<=seconds<=300 or seconds%15: raise RuntimeError(f'invalid duration {seconds}')
    env=dict(os.environ); env['KAGGLE_API_TOKEN']=token
    publish_inputs(env,image,audio,seconds)
    run_id=os.getenv('GITHUB_RUN_ID','manual')
    for attempt in (1,2):
        kernel=f'{KERNEL_PREFIX}-{run_id}-{attempt}'.lower()
        print(f'MUSETALK_KERNEL={kernel}',flush=True)
        ok,detail=run_kernel(env,kernel)
        if ok:
            dest=OUT/'kaggle_output'; shutil.rmtree(dest,ignore_errors=True); dest.mkdir(parents=True)
            run(['kaggle','kernels','output',kernel,'-p',str(dest),'--force','--file-pattern',r'.*master\.mp4$'],env)
            files=list(dest.rglob('master.mp4'))
            if not files: raise RuntimeError('KAGGLE_COMPLETED_BUT_MASTER_MP4_MISSING')
            shutil.copy2(files[0],OUT/'master.mp4')
            print('KAGGLE_MUSETALK_MASTER_READY',flush=True)
            return
        print(detail,flush=True)
        if attempt==1:
            print('MUSETALK_AUTO_RETRY=1 terminal Kaggle state; using a fresh kernel slug',flush=True)
            time.sleep(60)
    raise RuntimeError('KAGGLE_MUSETALK_KERNEL_FAILED_AFTER_RETRY')

if __name__=='__main__':
    import argparse
    ap=argparse.ArgumentParser(); ap.add_argument('--seconds',type=int,default=180)
    main(ap.parse_args().seconds)
