from __future__ import annotations

import json
import os
import shutil
import subprocess
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'output'
KDIR = ROOT / '.kaggle_worker'
DDIR = ROOT / '.kaggle_dataset'
FLASH_DDIR = ROOT / '.kaggle_flash_dataset'
KERNEL = 'bhajanaabha/hindibhajans-echomimic-v3'
INPUT_DATASET = 'bhajanaabha/hindibhajans-echomimic-inputs'
FLASH_DATASET = 'bhajanaabha/hindibhajans-echomimic-flash'
WAN_MODEL = 'mahbubahmedturza/wan-ai-new/Other/default/1'
WORKER_SOURCE = ROOT / 'app' / 'kaggle_echomimic_worker.py'


def run(cmd: list[str], *, env: dict[str, str], check: bool = True) -> subprocess.CompletedProcess[str]:
    print('RUN:', *cmd, flush=True)
    return subprocess.run(cmd, cwd=ROOT, env=env, text=True, check=check)


def wait_dataset(env: dict[str, str], timeout: int = 900) -> None:
    deadline = time.time() + timeout
    while time.time() < deadline:
        p = subprocess.run(
            ['kaggle', 'datasets', 'status', INPUT_DATASET, '--format', 'json'],
            cwd=ROOT, env=env, capture_output=True, text=True,
        )
        text = (p.stdout + p.stderr).strip()
        print('DATASET_STATUS', text, flush=True)
        if p.returncode == 0:
            low = text.lower()
            if 'complete' in low or 'ready' in low or 'success' in low:
                return
            if 'error' in low or 'failed' in low or 'cancelled' in low or 'canceled' in low:
                raise RuntimeError(f'KAGGLE_DATASET_FAILED: {text}')
        time.sleep(15)
    raise TimeoutError('KAGGLE_DATASET_TIMEOUT')


def publish_input_dataset(env: dict[str, str], image: Path, audio: Path, seconds: int) -> None:
    shutil.rmtree(DDIR, ignore_errors=True)
    DDIR.mkdir(parents=True)
    shutil.copy2(image, DDIR / 'singer.png')
    shutil.copy2(audio, DDIR / 'bhajan.mp3')
    (DDIR / 'duration.txt').write_text(str(seconds))
    (DDIR / 'dataset-metadata.json').write_text(json.dumps({
        'title': 'HindiBHajans EchoMimic Runtime Inputs',
        'id': INPUT_DATASET,
        'subtitle': 'Private per-run inputs for the HindiBHajans EchoMimic video worker',
        'description': 'Private runtime input package generated by GitHub Actions for one HindiBHajans production run.',
        'licenses': [{'name': 'other'}],
    }, indent=2))

    status = subprocess.run(
        ['kaggle', 'datasets', 'status', INPUT_DATASET, '--format', 'json'],
        cwd=ROOT, env=env, capture_output=True, text=True,
    )
    if status.returncode == 0:
        run(['kaggle', 'datasets', 'version', '-p', str(DDIR), '-m', f'Runtime inputs {seconds}s', '-d'], env=env)
    else:
        run(['kaggle', 'datasets', 'create', '-p', str(DDIR)], env=env)
    wait_dataset(env)
    print('KAGGLE_INPUT_DATASET_READY', INPUT_DATASET, flush=True)


def wait_dataset_handle(env: dict[str, str], dataset: str, timeout: int = 1800) -> None:
    deadline = time.time() + timeout
    while time.time() < deadline:
        p = subprocess.run(
            ['kaggle', 'datasets', 'status', dataset, '--format', 'json'],
            cwd=ROOT, env=env, capture_output=True, text=True,
        )
        text = (p.stdout + p.stderr).strip()
        print('DATASET_STATUS', dataset, text, flush=True)
        if p.returncode == 0:
            low = text.lower()
            if 'complete' in low or 'ready' in low or 'success' in low:
                return
            if 'error' in low or 'failed' in low or 'cancelled' in low or 'canceled' in low:
                raise RuntimeError(f'KAGGLE_DATASET_FAILED: {dataset}: {text}')
        time.sleep(15)
    raise TimeoutError(f'KAGGLE_DATASET_TIMEOUT: {dataset}')

def ensure_flash_dataset(env: dict[str, str]) -> None:
    status = subprocess.run(
        ['kaggle', 'datasets', 'status', FLASH_DATASET, '--format', 'json'],
        cwd=ROOT, env=env, capture_output=True, text=True,
    )
    if status.returncode == 0 and any(x in (status.stdout + status.stderr).lower() for x in ('complete', 'ready', 'success')):
        files = subprocess.run(
            ['kaggle', 'datasets', 'files', FLASH_DATASET, '--page-size', '20'],
            cwd=ROOT, env=env, capture_output=True, text=True,
        )
        if 'diffusion_pytorch_model.safetensors' in (files.stdout + files.stderr):
            print('KAGGLE_FLASH_DATASET_READY', FLASH_DATASET, flush=True)
            return
    shutil.rmtree(FLASH_DDIR, ignore_errors=True)
    (FLASH_DDIR).mkdir(parents=True, exist_ok=True)
    flash_file = FLASH_DDIR / 'diffusion_pytorch_model.safetensors'
    flash_config = FLASH_DDIR / 'config.json'
    expected_size = 3_727_671_120
    expected_sha256 = '5ebdbb2fc709108bf2a1728fd92eb2874804e4bc0324e92a2cd55425968c85a4'
    flash_url = 'https://huggingface.co/BadToBest/EchoMimicV3/resolve/main/echomimicv3-flash-pro/diffusion_pytorch_model.safetensors?download=true'
    config_url = 'https://huggingface.co/BadToBest/EchoMimicV3/resolve/main/echomimicv3-flash-pro/config.json?download=true'
    print('KAGGLE_FLASH_DATASET_PREPARE', FLASH_DATASET, flush=True)
    run(['df', '-h', str(ROOT)], env=env)
    run(['curl', '-L', '--fail', '--retry', '5', '--retry-all-errors', '--retry-delay', '3', '--connect-timeout', '30', '--max-time', '1800', '-o', str(flash_file), flash_url], env=env)
    run(['curl', '-L', '--fail', '--retry', '5', '--retry-all-errors', '--retry-delay', '2', '--connect-timeout', '30', '--max-time', '120', '-o', str(flash_config), config_url], env=env)
    if flash_file.stat().st_size != expected_size:
        raise RuntimeError(f'GITHUB_FLASH_SIZE_MISMATCH: expected={expected_size} actual={flash_file.stat().st_size}')
    import hashlib
    digest = hashlib.sha256()
    with flash_file.open('rb') as fh:
        for block in iter(lambda: fh.read(16 * 1024 * 1024), b''):
            digest.update(block)
    actual = digest.hexdigest()
    print('GITHUB_FLASH_SHA256', actual, flush=True)
    if actual != expected_sha256:
        raise RuntimeError(f'GITHUB_FLASH_SHA256_MISMATCH: expected={expected_sha256} actual={actual}')
    (FLASH_DDIR / 'dataset-metadata.json').write_text(json.dumps({
        'title': 'HindiBHajans EchoMimicV3 Flash',
        'id': FLASH_DATASET,
        'subtitle': 'Official EchoMimicV3 Flash transformer checkpoint',
        'description': 'Official BadToBest/EchoMimicV3 echomimicv3-flash-pro transformer checkpoint.',
        'licenses': [{'name': 'apache-2.0'}],
    }, indent=2))
    if status.returncode == 0:
        run(['kaggle', 'datasets', 'version', '-p', str(FLASH_DDIR), '-m', 'Official EchoMimicV3 Flash checkpoint', '-d'], env=env)
    else:
        run(['kaggle', 'datasets', 'create', '-p', str(FLASH_DDIR)], env=env)
    wait_dataset_handle(env, FLASH_DATASET)
    print('KAGGLE_FLASH_DATASET_READY', FLASH_DATASET, flush=True)

def main(seconds: int) -> None:
    token = os.getenv('KAGGLE_API_TOKEN') or os.getenv('KAGGLE_API_TOKEN3')
    if not token:
        raise RuntimeError('KAGGLE_API_TOKEN missing')
    image = ROOT / 'assets' / 'singer_image.png'
    audio = OUT / 'bhajan_source.mp3'
    if not image.exists() or not audio.exists():
        raise RuntimeError('canonical inputs missing')
    if not 180 <= seconds <= 300 or seconds % 15:
        raise RuntimeError(f'invalid duration: {seconds}')
    if not WORKER_SOURCE.exists():
        raise RuntimeError(f'worker source missing: {WORKER_SOURCE}')

    env = dict(os.environ)
    env['KAGGLE_API_TOKEN'] = token

    publish_input_dataset(env, image, audio, seconds)
    ensure_flash_dataset(env)

    shutil.rmtree(KDIR, ignore_errors=True)
    KDIR.mkdir(parents=True)
    shutil.copy2(WORKER_SOURCE, KDIR / 'worker.py')
    metadata = {
        'id': KERNEL,
        'title': 'hindibhajans-echomimic-v3',
        'code_file': 'worker.py',
        'language': 'python',
        'kernel_type': 'script',
        'is_private': True,
        'enable_gpu': True,
        'enable_internet': True,
        'machine_shape': 'NvidiaTeslaT4',
        'dataset_sources': [INPUT_DATASET, FLASH_DATASET],
        'competition_sources': [],
        'kernel_sources': [],
        'model_sources': [WAN_MODEL],
    }
    (KDIR / 'kernel-metadata.json').write_text(json.dumps(metadata, indent=2))

    run(['python', '-m', 'py_compile', str(KDIR / 'worker.py')], env=env)
    worker_bytes = (KDIR / 'worker.py').stat().st_size
    print('KAGGLE_WORKER_PACKAGE', f'worker_bytes={worker_bytes}', f'WAN_MODEL_SOURCE={WAN_MODEL}', f'FLASH_DATASET_SOURCE={FLASH_DATASET}', flush=True)
    if worker_bytes > 100_000:
        raise RuntimeError(f'WORKER_SOURCE_TOO_LARGE: {worker_bytes}')

    def push_and_wait() -> tuple[bool, str]:
        run(['kaggle', 'kernels', 'push', '-p', str(KDIR), '--timeout', '39600'], env=env)
        deadline = time.time() + 39600
        while time.time() < deadline:
            p = subprocess.run(
                ['kaggle', 'kernels', 'status', KERNEL],
                capture_output=True,
                text=True,
                env=env,
            )
            status = (p.stdout + p.stderr).strip()
            print(status, flush=True)
            t = status.lower()
            if 'complete' in t and not any(x in t for x in ('incomplete', 'not complete')):
                return True, status
            if any(x in t for x in ('error', 'failed', 'cancelled', 'canceled')):
                log = subprocess.run(
                    ['kaggle', 'kernels', 'logs', KERNEL],
                    capture_output=True,
                    text=True,
                    env=env,
                )
                return False, (log.stdout or log.stderr or 'KAGGLE_KERNEL_LOG_EMPTY')
            time.sleep(30)
        raise TimeoutError('KAGGLE_KERNEL_TIMEOUT')

    ok, failure_text = push_and_wait()
    if not ok and 'FLASH_DATASET_NOT_MOUNTED' in failure_text:
        print('KAGGLE_FLASH_DATASET_RETRY=1', flush=True)
        ok, failure_text = push_and_wait()
    if not ok:
        print(failure_text, flush=True)
        raise RuntimeError('KAGGLE_KERNEL_FAILED')

    dest = OUT / 'kaggle_output'
    shutil.rmtree(dest, ignore_errors=True)
    dest.mkdir(parents=True)
    run(
        ['kaggle', 'kernels', 'output', KERNEL, '-p', str(dest), '--force', '--file-pattern', r'.*master\.mp4$'],
        env=env,
    )
    files = list(dest.rglob('master.mp4'))
    if not files:
        raise RuntimeError('KAGGLE_COMPLETED_BUT_MASTER_MP4_MISSING')
    shutil.copy2(files[0], OUT / 'master.mp4')
    print('KAGGLE_ECHOMIMIC_MASTER_READY', flush=True)


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('--seconds', type=int, default=180)
    main(parser.parse_args().seconds)
