from __future__ import annotations

import json
import os
import shutil
import subprocess
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'output'
KDIR = ROOT / '.kaggle_worker'
DDIR = ROOT / '.kaggle_dataset'
KERNEL = 'bhajanaabha/hindibhajans-echomimic-v3'
INPUT_DATASET = 'bhajanaabha/hindibhajans-echomimic-inputs'
WAN_BASE_MODEL = 'mahbubahmedturza/wan-ai-new/Other/default/1'
WORKER_SOURCE = ROOT / 'app' / 'kaggle_echomimic_worker.py'


def run(cmd: list[str], *, env: dict[str, str], check: bool = True) -> subprocess.CompletedProcess[str]:
    print('RUN:', *cmd, flush=True)
    return subprocess.run(cmd, cwd=ROOT, env=env, text=True, check=check)


def wait_dataset(env: dict[str, str], timeout: int = 900) -> None:
    deadline = time.time() + timeout
    while time.time() < deadline:
        p = subprocess.run(
            ['kaggle', 'datasets', 'status', INPUT_DATASET, '--format', 'json'],
            cwd=ROOT, env=env, capture_output=True, text=True,
        )
        text = (p.stdout + p.stderr).strip()
        print('DATASET_STATUS', text, flush=True)
        if p.returncode == 0:
            low = text.lower()
            if 'complete' in low or 'ready' in low or 'success' in low:
                return
            if 'error' in low or 'failed' in low or 'cancelled' in low or 'canceled' in low:
                raise RuntimeError(f'KAGGLE_DATASET_FAILED: {text}')
        time.sleep(15)
    raise TimeoutError('KAGGLE_DATASET_TIMEOUT')


def publish_input_dataset(env: dict[str, str], image: Path, audio: Path, seconds: int) -> None:
    shutil.rmtree(DDIR, ignore_errors=True)
    DDIR.mkdir(parents=True)
    shutil.copy2(image, DDIR / 'singer.png')
    shutil.copy2(audio, DDIR / 'bhajan.mp3')
    (DDIR / 'duration.txt').write_text(str(seconds))
    (DDIR / 'dataset-metadata.json').write_text(json.dumps({
        'title': 'HindiBHajans EchoMimic Runtime Inputs',
        'id': INPUT_DATASET,
        'subtitle': 'Private per-run inputs for the HindiBHajans EchoMimic video worker',
        'description': 'Private runtime input package generated by GitHub Actions for one HindiBHajans production run.',
        'licenses': [{'name': 'other'}],
    }, indent=2))

    status = subprocess.run(
        ['kaggle', 'datasets', 'status', INPUT_DATASET, '--format', 'json'],
        cwd=ROOT, env=env, capture_output=True, text=True,
    )
    if status.returncode == 0:
        run(['kaggle', 'datasets', 'version', '-p', str(DDIR), '-m', f'Runtime inputs {seconds}s', '-d'], env=env)
    else:
        run(['kaggle', 'datasets', 'create', '-p', str(DDIR)], env=env)
    wait_dataset(env)
    print('KAGGLE_INPUT_DATASET_READY', INPUT_DATASET, flush=True)


def main(seconds: int) -> None:
    token = os.getenv('KAGGLE_API_TOKEN') or os.getenv('KAGGLE_API_TOKEN3')
    if not token:
        raise RuntimeError('KAGGLE_API_TOKEN missing')
    image = ROOT / 'assets' / 'singer_image.png'
    audio = OUT / 'bhajan_source.mp3'
    if not image.exists() or not audio.exists():
        raise RuntimeError('canonical inputs missing')
    if not 180 <= seconds <= 300 or seconds % 15:
        raise RuntimeError(f'invalid duration: {seconds}')
    if not WORKER_SOURCE.exists():
        raise RuntimeError(f'worker source missing: {WORKER_SOURCE}')

    env = dict(os.environ)
    env['KAGGLE_API_TOKEN'] = token

    publish_input_dataset(env, image, audio, seconds)

    shutil.rmtree(KDIR, ignore_errors=True)
    KDIR.mkdir(parents=True)
    shutil.copy2(WORKER_SOURCE, KDIR / 'worker.py')
    metadata = {
        'id': KERNEL,
        'title': 'hindibhajans-echomimic-v3',
        'code_file': 'worker.py',
        'language': 'python',
        'kernel_type': 'script',
        'is_private': True,
        'enable_gpu': True,
        'enable_internet': True,
        'machine_shape': 'NvidiaTeslaT4',
        'dataset_sources': [INPUT_DATASET],
        'competition_sources': [],
        'kernel_sources': [],
        # Public Kaggle model: ~16.66 GB of Wan2.1 T2V-1.3B base components.
        # Mounting it as an input keeps it off the ~20 GB writable disk.
        'model_sources': [WAN_BASE_MODEL],
    }
    (KDIR / 'kernel-metadata.json').write_text(json.dumps(metadata, indent=2))

    run(['python', '-m', 'py_compile', str(KDIR / 'worker.py')], env=env)
    worker_bytes = (KDIR / 'worker.py').stat().st_size
    print('KAGGLE_WORKER_PACKAGE', f'worker_bytes={worker_bytes}', flush=True)
    if worker_bytes > 100_000:
        raise RuntimeError(f'WORKER_SOURCE_TOO_LARGE: {worker_bytes}')

    run(['kaggle', 'kernels', 'push', '-p', str(KDIR), '--timeout', '39600'], env=env)

    deadline = time.time() + 39600
    while time.time() < deadline:
        p = subprocess.run(
            ['kaggle', 'kernels', 'status', KERNEL],
            capture_output=True,
            text=True,
            env=env,
        )
        status = (p.stdout + p.stderr).strip()
        print(status, flush=True)
        t = status.lower()
        if 'complete' in t and not any(x in t for x in ('incomplete', 'not complete')):
            break
        if any(x in t for x in ('error', 'failed', 'cancelled', 'canceled')):
            log = subprocess.run(
                ['kaggle', 'kernels', 'logs', KERNEL],
                capture_output=True,
                text=True,
                env=env,
            )
            print(log.stdout or log.stderr or 'KAGGLE_KERNEL_LOG_EMPTY', flush=True)
            raise RuntimeError('KAGGLE_KERNEL_FAILED')
        time.sleep(30)
    else:
        raise TimeoutError('KAGGLE_KERNEL_TIMEOUT')

    dest = OUT / 'kaggle_output'
    shutil.rmtree(dest, ignore_errors=True)
    dest.mkdir(parents=True)
    run(
        ['kaggle', 'kernels', 'output', KERNEL, '-p', str(dest), '--force', '--file-pattern', r'.*master\.mp4$'],
        env=env,
    )
    files = list(dest.rglob('master.mp4'))
    if not files:
        raise RuntimeError('KAGGLE_COMPLETED_BUT_MASTER_MP4_MISSING')
    shutil.copy2(files[0], OUT / 'master.mp4')
    print('KAGGLE_ECHOMIMIC_MASTER_READY', flush=True)


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('--seconds', type=int, default=180)
    main(parser.parse_args().seconds)
